name: demo_app
description: A new Flutter application.


version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
 ## cloud_firestore: ^0.12.10
  firebase_core: ^0.4.1+2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Black.ttf
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Cinzel-Regular.ttf
        - asset: fonts/BalooBhai-Regular.ttf
